apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- datapower-service.yaml

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    datapower.build: hello

configMapGenerator:
- name: auto-startup-cfg
  behavior: create
  files:
  - gen/config/auto-startup.cfg

- name: auto-user-cfg
  behavior: create
  files:
  - gen/config/auto-user.cfg

- name: default-cfg
  behavior: create
  files:
  - gen/config/default.cfg

- name: default-local-tgz
  behavior: create
  files:
  - gen/test-local.tar.gz

- name: test-cfg
  behavior: create
  files:
  - gen/config/test/test.cfg

- name: test-local-tgz
  behavior: create
  files:
  - gen/test-local.tar.gz
